version: "3.9"

services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/opt/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
    networks:
      - off-time-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - off-time-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - off-time-network

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/opt/app
      - bundle:/usr/local/bundle
    env_file: .env
    entrypoint: ./bin/sidekiq-entrypoint.sh
    networks:
      - off-time-network

volumes:
  mysql_data:
  redis_data:
  bundle:

networks:
  off-time-network:
    
